### ISSUE TITLE
Missing to update startTime state variable in unstake function at PmknFarm.sol contract

### ISSUE THREAD

**Issue by mobydickfinance** [andrew-fleming/pmkn-farm#8]
First of all I apologize in case this is not the way to contribute. I am new at Github.

I think that in the following contract there is a bug that affects the calculation of yield:
https://github.com/andrew-fleming/pmkn-farm/blob/main/contracts/PmknFarm.sol

In the unstake() function is missing to update the startTime state variable. It calculates the yield of the balance before unstaking and accrues it to the pmknBalance state variable. If startTime[msg.sender] = block.timestamp; is not included, the left balance after unstake would generate duplicate yield.

Hope to be useful. Regards.

**Comment by andrew-fleming** [comment]
No worries @mobydickfinance! You are correct. Thank you for catching that. If you'd like to fix the bug and have a pull request credit, here's a [template](https://github.com/embeddedartistry/templates/blob/master/oss_docs/PULL_REQUEST_TEMPLATE.md). This is not a giant project; therefore, you can keep it simple--just include the issue number. Otherwise, let me know and I can add it in instead.

**Comment by mobydickfinance** [comment]
Ok Andrew. I will try with the template. I let you know if I have success. Thank you very much!!!

**Comment by andrew-fleming** [comment]
Thank you @mobydickfinance! Since you're new to working with GitHub, here's a good article I found for submitting PR's [here](https://www.freecodecamp.org/news/how-to-submit-a-pull-request-529efe82eea5/). Feel free to reach out with any questions

**Comment by mobydickfinance** [comment]
Hi Andrew. I really still do not catch how to do it. Is more difficult than programming in solidity. Please feel free to add it. Thanks!

**Comment by andrew-fleming** [comment]
No worries. Thanks again for the heads up @mobydickfinance!
